export interface BlogPost {
    id: string;
    title: string;
    excerpt: string;
    date: string;
    readTime: string;
    tags: string[];
    icon: string;
    iconColor: string;
    content?: string;
    isLegalDoc?: boolean;
    externalLink?: string;
}

export const blogPosts: BlogPost[] = [
    {
        id: "ai-analytics-multiplier",
        title: "AI × Analytics: Why 20% of Companies Are Capturing 75% of AI's Economic Value",
        excerpt:
            "Stanford's 2026 AI Index and PwC's AI Performance Study reveal a striking truth: the gap between AI winners and losers isn't about model quality — it's about analytics. Here's what the data says and how builders can position themselves at the most powerful intersection in tech.",
        date: "April 15, 2026",
        readTime: "14 min read",
        tags: ["AI/ML", "Business Analytics", "Generative AI", "AI Strategy", "Stanford AI Index", "Production AI", "AI ROI"],
        icon: "TrendingUp",
        iconColor: "blue",
    },
    {
        id: "anthropic-q1-2026",
        title: "Anthropic Shipped 20+ Major Updates in 3 Months - Here's What Builders Need to Know",
        excerpt:
            "From Claude Cowork and Opus 4.6 to Computer Use and 1M context windows, Anthropic's Q1 2026 was a masterclass in shipping. A deep dive into every major release, what it means for builders, and why the gap between AI users and AI builders is widening every week.",
        date: "March 31, 2026",
        readTime: "18 min read",
        tags: ["AI/ML", "Anthropic", "Claude Code", "Claude", "Agentic AI", "Developer Tools", "MCP", "Production AI"],
        icon: "Zap",
        iconColor: "orange",
    },
    {
        id: "a2a-agent-protocol",
        title: "A2A Protocol: How Google's Agent-to-Agent Standard Is Redefining Multi-Agent AI in 2026",
        excerpt:
            "Google's Agent-to-Agent (A2A) protocol is quietly becoming the TCP/IP of the agentic era — a universal standard that lets AI agents from different vendors, frameworks, and clouds communicate, negotiate, and collaborate. Here's what it is, how it works, and why every AI engineer needs to understand it right now.",
        date: "March 13, 2026",
        readTime: "15 min read",
        tags: ["AI Agents", "A2A", "Multi-Agent", "Agentic AI", "Google", "MCP", "Production AI", "Agent Protocols"],
        icon: "Share2",
        iconColor: "blue",
    },
    {
        id: "prompt-injection",
        title: "Prompt Injection: The Silent Exploit Threatening Every AI Application",
        excerpt:
            "Prompt injection is the top attack vector for LLM-powered applications — and most developers are still shipping vulnerable code. Learn how attackers hijack AI systems, the real-world breaches that prove the threat is live, and the layered defenses every AI engineer must implement in 2026.",
        date: "March 11, 2026",
        readTime: "16 min read",
        tags: ["AI/ML", "Cybersecurity", "LLM Security", "Prompt Injection", "AI Safety", "Production AI"],
        icon: "Shield",
        iconColor: "red",
    },
    {
        id: "tech-monthly-digest-mar-2026",
        title: "Tech Monthly Digest: March 2026 – The Model Avalanche, Sora's Death, and Agentic Infrastructure Comes of Age",
        excerpt:
            "March 2026 was the month AI stopped being cyclical and became perpetual. Twelve frontier models shipped in a single week. OpenAI killed Sora and acquired Astral. Anthropic leaked a model and its own source code. Meta's Llama 4 went open source and beat GPT-4o. AWS AgentCore and Google ADK 1.0 made production agents real. Here's everything that mattered for builders.",
        date: "April 1, 2026",
        readTime: "20 min read",
        tags: ["AI/ML", "Agents", "Monthly Digest", "LLMs", "Developer Tools", "Cloud AI", "Open Source", "AI Policy"],
        icon: "Globe",
        iconColor: "purple",
    },
    {
        id: "tech-monthly-digest-feb-2026",
        title: "Tech Monthly Digest: February 2026 – A2A, Context Engineering, and the Rise of Agentic Everything",
        excerpt:
            "February 2026 was the month agentic AI stopped being experimental and started being expected. Google's A2A protocol redefined how agents communicate, Context Engineering emerged as the must-have production skill, MCP became the de facto standard for tool use, and every major cloud doubled down on inference infrastructure. Here's everything that mattered for builders this month.",
        date: "March 1, 2026",
        readTime: "18 min read",
        tags: ["AI/ML", "Agents", "A2A", "MCP", "Context Engineering", "Developer Tools", "Monthly Digest"],
        icon: "Globe",
        iconColor: "purple",
    },
    {
        id: "context-engineering",
        title: "Context Engineering: The Skill That Replaced Prompt Engineering for Production AI in 2026",
        excerpt:
            "Prompt engineering got you started. Context engineering gets you to production. Learn why the most critical skill for building reliable AI agents and enterprise LLM applications in 2026 is no longer what you say to the model — it's what the model knows when it starts thinking.",
        date: "February 13, 2026",
        readTime: "16 min read",
        tags: ["AI/ML", "Context Engineering", "Prompt Engineering", "LLM", "AI Agents", "Production AI", "RAG"],
        icon: "BrainCircuit",
        iconColor: "purple",
    },
    {
        id: "tech-monthly-digest-jan-2026",
        title: "Tech Monthly Digest: January 2026 – Agents, IDEs, and Cloud AI in Motion",
        excerpt:
            "January 2026 pushed AI development from \"nice-to-have assistants\" to always-on engineering teammates. From GPT-5.1 in production tools to agent-first IDEs and maturing orchestration frameworks, this monthly digest highlights the updates that actually matter for builders.",
        date: "February 1, 2026",
        readTime: "15 min read",
        tags: ["AI/ML", "Agents", "Developer Tools", "Cloud Computing", "BiWeekly Digest"],
        icon: "Globe",
        iconColor: "purple",
    },
    {
        id: "cursor-ai",
        title: "Cursor: The AI-Native IDE Redefining How Developers Ship Software",
        excerpt: "Cursor is an AI-first IDE that combines full-project understanding, agentic workflows, and powerful model integrations to help developers ship features, refactors, and fixes dramatically faster in 2025–2026.",
        date: "January 28, 2026",
        readTime: "16 min read",
        tags: ["AI/ML", "Developer Tools", "IDEs", "AI Coding", "Agents", "Productivity"],
        icon: "Code2",
        iconColor: "blue",
    },
    {
        id: "openai-codex",
        title: "OpenAI Codex: The Cloud-Native AI Coding Agent Reshaping Software Engineering",
        excerpt: "OpenAI Codex is a cloud-based AI coding agent that runs in a sandboxed environment, handling tasks like writing features, fixing bugs, and answering codebase questions in parallel, bringing a new paradigm to software development in 2025.",
        date: "January 20, 2026",
        readTime: "13 min read",
        tags: ["AI/ML", "Developer Tools", "Coding Assistant", "Cloud Computing", "Productivity"],
        icon: "Robot",
        iconColor: "green",
    },
    {
        id: "claude-code",
        title: "Claude Code: Anthropic's AI-Powered CLI That Changes How You Write Software",
        excerpt: "Claude Code is Anthropic's agentic coding tool that lives in your terminal. It understands your entire codebase, edits files, runs commands, and handles complex multi-step engineering tasks, redefining what developer productivity looks like in 2025.",
        date: "January 15, 2026",
        readTime: "14 min read",
        tags: ["AI/ML", "Developer Tools", "CLI", "Coding Assistant", "Productivity"],
        icon: "Terminal",
        iconColor: "orange",
    },
    {
        id: "biweekly-tech-2025-11-23-12-07",
        title: "Biweekly Tech Radar: AI Agents, Foundation Models, and Infra",
        excerpt: "From GPT-5.1 and Gemini 3 to massive AI infrastructure deals and multimodal agents, late November 2025 was packed with launches that are quietly redefining what 'production AI' means. This biweekly digest cuts through the noise and focuses on what matters for builders.",
        date: "December 7, 2025",
        readTime: "15 min read",
        tags: ["AI/ML", "Foundation Models", "Agents", "Cloud", "Infra", "Productivity"],
        icon: "Globe",
        iconColor: "purple",
    },
    {
        id: "modern-ides-2025",
        title: "Mastering Modern IDEs in 2025: VS Code, Cursor, Kiro, and Antigravity",
        excerpt: "Explore how VS Code, Cursor, Kiro, and Google Antigravity are reshaping the developer experience\u2014from lightweight code editing to fully agentic AI-driven workflows.",
        date: "December 03, 2025",
        readTime: "15 min read",
        tags: ["IDEs", "VS Code", "Cursor", "Kiro", "Antigravity", "AI Coding", "AI", "Tools"],
        icon: "Code2",
        iconColor: "blue",
    },
    {
        id: "weekly-novmid",
        title: "Tech BiWeekly Digest: November 11\u201323, 2025",
        excerpt: "This edition covers key developments in AI and cloud infrastructure, highlighting OpenAI's GPT-5.1 launch, LangChain's production advances, Gemini's new features, and AWS's expanding AI toolkit.",
        date: "November 23, 2025",
        readTime: "15 min read",
        tags: ["AI/ML", "OpenAI", "Cloud Computing", "BiWeekly Digest"],
        icon: "BookOpen",
        iconColor: "green",
    },
    {
        id: "coding-journey",
        title: "From Zero to 3-Star: My 8-Month Journey to 2100+ LeetCode Rating & 1000+ DSA Problems",
        excerpt: "How I went from knowing nothing about competitive programming in April 2025 to achieving 3-star on CodeChef, 2100+ rating on LeetCode, and solving 1000+ DSA problems by November 2025. A raw, honest account of the struggles, strategies, and breakthroughs.",
        date: "November 19, 2025",
        readTime: "15 min read",
        tags: ["DSA", "Competitive Programming", "LeetCode", "CodeChef", "Learning Journey", "Career Growth"],
        icon: "Trophy",
        iconColor: "purple",
    },
    {
        id: "langchain",
        title: "LangChain: The Orchestration Layer for Production-Grade AI Applications",
        excerpt: "LangChain transforms raw LLMs into reliable, multi-tool AI applications by enabling complex workflows, memory management, and seamless integration with vector databases.",
        date: "November 18, 2025",
        readTime: "20 min read",
        tags: ["AI/ML", "LangChain", "RAG", "LLM", "Vector Databases", "AI Orchestration"],
        icon: "PuzzlePiece",
        iconColor: "purple",
    },
    {
        id: "n8n",
        title: "Unlocking Automation Power with n8n: The Open-Source Workflow Automation Tool",
        excerpt: "Discover how n8n's open-source, flexible automation platform is transforming businesses by enabling powerful workflows without extensive coding. Learn its features, use cases, and how to get started.",
        date: "November 13, 2025",
        readTime: "12 min read",
        tags: ["Automation", "n8n", "Workflow Automation", "Open Source", "DevOps"],
        icon: "PuzzlePiece",
        iconColor: "teal",
    },
    {
        id: "weekly-nov3",
        title: "Tech BiWeekly Digest: Week of November 3, 2025",
        excerpt: "Welcome to your go-to digest for the latest upheavals and breakthroughs in GenAI, developer frameworks, and cloud infrastructure. This edition deciphers fresh updates from OpenAI, LangChain, Gemini, and more.",
        date: "November 9, 2025",
        readTime: "15 min read",
        tags: ["AI/ML", "OpenAI", "Cloud Computing", "BiWeekly Digest"],
        icon: "BookOpen",
        iconColor: "green",
    },
    {
        id: "vector-database",
        title: "Vector Databases: The Foundation of Modern AI Applications",
        excerpt: "The rise of generative AI and large language models has fundamentally transformed how we store and retrieve data. Traditional databases struggle with the demands of modern AI workloads. Enter vector databases\u2014a paradigm shift in data management that's quietly becoming table stakes for any organization building AI-native applications.",
        date: "November 5, 2025",
        readTime: "20 min read",
        tags: ["Vector Databases", "AI/ML", "Embeddings", "Semantic Search", "RAG", "Database Technology"],
        icon: "Database",
        iconColor: "purple",
    },
    {
        id: "weekly-oct20",
        title: "Tech BiWeekly Digest: Week of October 20, 2025",
        excerpt: "Welcome to the inaugural edition of Tech BiWeekly Digest\u2014your Sunday morning companion for staying current with the rapidly evolving world of GenAI, cloud computing, and emerging technologies.",
        date: "October 26, 2025",
        readTime: "15 min read",
        tags: ["AI/ML", "OpenAI", "Cloud Computing", "BiWeekly Digest"],
        icon: "BookOpen",
        iconColor: "green",
    },
    {
        id: "fine-tuning-llms",
        title: "Fine-Tuning Large Language Models: Techniques, Trends, and Best Practices in 2025",
        excerpt: "Fine-tuning Large Language Models (LLMs) is a powerful way to adapt general-purpose AI models to specialized tasks or domains. This blog explores the latest fine-tuning techniques, their benefits, challenges, and practical steps to optimize LLM performance in 2025.",
        date: "October 20, 2025",
        readTime: "11 min read",
        tags: ["AI/ML", "LLM", "Fine-Tuning", "NLP", "AI Innovation"],
        icon: "AdjustmentsHorizontal",
        iconColor: "orange",
    },
    {
        id: "rag",
        title: "Retrieval-Augmented Generation: Transforming How LLMs Access Knowledge",
        excerpt: "Large Language Models have revolutionized how we interact with AI, but they face a fundamental limitation: their knowledge is frozen at the time of training. RAG emerged as the solution to this challenge, fundamentally changing how we build production AI applications.",
        date: "October 15, 2025",
        readTime: "25 min read",
        tags: ["AI/ML", "RAG", "LLM", "Vector Databases", "Production AI", "Knowledge Management"],
        icon: "Database",
        iconColor: "blue",
    },
    {
        id: "llm-poisoning",
        title: "LLM Poisoning: The Hidden Threat to AI Trustworthiness",
        excerpt: "LLM poisoning is a rising cybersecurity concern where attackers subtly corrupt the data used to train large language models, causing these AI systems to behave unpredictably or dangerously. Recent research shows that it takes only a small number of poisoned documents to impact even the largest models.",
        date: "October 13, 2025",
        readTime: "12 min read",
        tags: ["AI/ML", "Cybersecurity", "LLM Security", "Data Poisoning", "AI Safety"],
        icon: "Shield",
        iconColor: "red",
    },
    {
        id: "llm-hallucination",
        title: "When AI Dreams: Understanding and Mitigating LLM Hallucinations",
        excerpt: "Explore why large language models hallucinate, real-world examples, and proven strategies to reduce these errors for reliable AI applications.",
        date: "October 10, 2025",
        readTime: "15 min read",
        tags: ["AI/ML", "LLM", "Hallucination", "AI Reliability", "RAG", "Prompt Engineering"],
        icon: "BrainCircuit",
        iconColor: "blue",
    },
    {
        id: "python",
        title: "Mastering Python in 2025: The Universal Language for Modern Development",
        excerpt: "Uncover why Python is the number one tool in 2025 for rapid development, automation, and data science. Explore core features, latest advancements, real-world use cases, and actionable best practices to build robust Python solutions.",
        date: "October 8, 2025",
        readTime: "14 min read",
        tags: ["Python", "Programming", "Data Science", "Automation", "Web Development"],
        icon: "PythonLogo",
        iconColor: "blue",
    },
    {
        id: "openai-agent-builder",
        title: "OpenAI Agent Builder: Building Smarter AI Agents Without Code",
        excerpt: "OpenAI Agent Builder is a breakthrough visual platform launched in 2025 that empowers developers and non-developers alike to create, test, and deploy intelligent multi-step AI agents quickly and securely. It combines drag-and-drop simplicity with enterprise-grade features, redefining AI automation workflows.",
        date: "October 7, 2025",
        readTime: "12 min read",
        tags: ["AI/ML", "OpenAI", "Agent Builder", "Automation", "No-Code AI"],
        icon: "Robot",
        iconColor: "teal",
    },
    {
        id: "mcp-servers",
        title: "MCP Servers: The Backbone of Intelligent AI Integration in 2025",
        excerpt: "Model Context Protocol (MCP) servers are revolutionizing AI applications by enabling seamless, secure, and scalable interaction between large language models and external data sources and systems. In 2025, they have become essential for building context-aware AI workflows across industries.",
        date: "September 25, 2025",
        readTime: "16 min read",
        tags: ["AI/ML", "MCP Servers", "Cloud Computing", "AI Integration", "Data Architecture"],
        icon: "ServerStack",
        iconColor: "indigo",
    },
    {
        id: "aws-bedrock",
        title: "Amazon Bedrock: Empowering Scalable and Secure Generative AI for Production in 2025",
        excerpt: "Amazon Bedrock provides serverless foundation models with enterprise-grade security and seamless AWS integration, transforming how organizations build and deploy generative AI applications.",
        date: "September 23, 2025",
        readTime: "22 min read",
        tags: ["AI/ML", "AWS Bedrock", "Generative AI", "Foundation Models", "Production AI", "Serverless AI"],
        icon: "Cloud",
        iconColor: "orange",
    },
    {
        id: "aws-lambda",
        title: "Mastering AWS Lambda in 2025: The Serverless Computing Revolution",
        excerpt: "Discover the latest capabilities of AWS Lambda, its transformative role in serverless computing, best practices, and how to build scalable applications on AWS with minimal operational burden.",
        date: "September 20, 2025",
        readTime: "15 min read",
        tags: ["Cloud Computing", "Serverless", "AWS Lambda", "Event-Driven Architecture", "AWS"],
        icon: "CloudServer",
        iconColor: "orange",
    },
    {
        id: "java",
        title: "Mastering Java in 2025: The Enduring Powerhouse of Modern Software",
        excerpt: "Explore why Java remains essential in 2025, the latest language updates, versatile use-cases, expert best practices, and how to build robust, maintainable Java applications from the ground up.",
        date: "September 17, 2025",
        readTime: "14 min read",
        tags: ["Java", "Programming", "Software Engineering", "Object-Oriented", "JVM"],
        icon: "JavaLogo",
        iconColor: "red",
    },
    {
        id: "cpp",
        title: "Mastering C++ in 2025: Power, Precision, and Performance for All Innovators",
        excerpt: "Explore C++'s ongoing evolution, from modern language features to high-performance applications. Learn key concepts, advanced best practices, and how to develop robust and efficient solutions with C++ in 2025.",
        date: "September 16, 2025",
        readTime: "16 min read",
        tags: ["C++", "Programming", "Systems Development", "Object-Oriented", "Performance"],
        icon: "CppLogo",
        iconColor: "indigo",
    },
    {
        id: "aws-sagemaker",
        title: "AWS SageMaker: The Complete Guide to Building, Training, and Deploying ML Models",
        excerpt: "AWS SageMaker is a fully managed machine learning platform that streamlines the entire ML lifecycle\u2014from data preparation and model training to deployment and monitoring. Discover how SageMaker empowers teams to build scalable, secure, and production-ready AI solutions.",
        date: "September 11, 2025",
        readTime: "12 min read",
        tags: ["AI/ML", "Cloud Computing", "AWS", "Machine Learning", "MLOps"],
        icon: "Cloud",
        iconColor: "blue",
    },
    {
        id: "llms",
        title: "Large Language Models in 2025: Trends, Breakthroughs, & Leading Examples",
        excerpt: "Large Language Models have transformed AI interactions across industries. This comprehensive 18-minute read explores the latest advancements, challenges, and future directions of LLMs while featuring top players like ChatGPT, Gemini, Claude, and Perplexity.",
        date: "September 9, 2025",
        readTime: "18 min read",
        tags: ["AI/ML", "Large Language Models", "NLP", "AI Trends", "Future of AI"],
        icon: "Language",
        iconColor: "green",
    },
    {
        id: "ai-vs-genai",
        title: "AI vs Generative AI: Understanding the Key Differences in 2025",
        excerpt: "Artificial Intelligence (AI) and Generative AI are often used interchangeably, but they represent distinct technologies with unique purposes and capabilities. This post unpacks their core differences, how they function, and why understanding both matters for today's tech landscape.",
        date: "August 31, 2025",
        readTime: "10 min read",
        tags: ["AI/ML", "Generative AI", "Technology", "Innovation"],
        icon: "BrainCircuit",
        iconColor: "purple",
    },
    {
        id: "dl-algorithms",
        title: "Deep Learning Algorithms in 2025: From MLP to Transformers and GANs",
        excerpt: "Explore the defining deep learning algorithms\u2014ANNs, CNNs, RNNs, LSTM, GRU, Transformers, Autoencoders, and GANs\u2014powering breakthroughs in AI today. Includes practical explanations, use cases, and Python starter syntax for each network.",
        date: "August 26, 2025",
        readTime: "15 min read",
        tags: ["Deep Learning", "Algorithms", "Neural Networks", "AI/ML", "Python"],
        icon: "CpuChip",
        iconColor: "purple",
    },
    {
        id: "ml-algorithms",
        title: "All Major Machine Learning Algorithms (2025): The Ultimate Guide to Paradigms, and Algorithms",
        excerpt: "Explore every major class of machine learning algorithms in 2025: supervised, unsupervised, semi-supervised, and reinforcement learning. This in-depth post lists all top algorithms in each paradigm and provides practical Python syntax to help you get started.",
        date: "August 25, 2025",
        readTime: "17 min read",
        tags: ["AI/ML", "Machine Learning", "Algorithms", "Python", "Data Science"],
        icon: "Chip",
        iconColor: "blue",
    },
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export const getBlogPost = (id: string): BlogPost | undefined => {
    return blogPosts.find((post) => post.id === id);
};

export const getFeaturedPosts = (): BlogPost[] => {
    return blogPosts.filter((post) => !post.isLegalDoc);
};

export const getLegalPosts = (): BlogPost[] => {
    return blogPosts.filter((post) => post.isLegalDoc);
};
