export const profileDetails = {
    name: "MARURI SAI RAMA LINGA REDDY",
    alternateName: "Sairam Maruri",
    brand: "Sairam Maruri",
    initials: "SAI RAMA LINGA REDDY MARURI",
    shortRole: "GenAI & ML Engineer",
    jobTitle: "GenAI & ML Engineer · Business Analytics",
    role: "GenAI & ML Engineer bridging AI systems and business analytics — turning data into decisions, and decisions into business impact.",
    summary:
        "Engineers build models. Analysts read dashboards. The value leaks in between — that gap is where I've decided to spend my career. I'm a Computer Science graduate (VIT-AP '26) and GenAI & ML engineer, now pursuing an MBA in Business Analytics at BITS Pilani and an MSc in Data Science at IIIT Hyderabad in parallel — fluent on both sides of the table where models meet business impact.",
    location: "",
    basedIn: "India",
    email: "sairam.maruri@gmail.com",
    phone: "+91 7893865644",
    resumeHref: "/Sai_Ram_Maruri_Resume_2025.pdf",
    availability: "Open to 2026 roles & internships",
    motto: "Learn always. Build always.",
    seekingRoles: ["Business Analyst", "Data Analyst", "Product Analyst", "AI/ML Engineer"],
    currentFocus: [
        "MBA in Business Analytics @ BITS Pilani",
        "MSc in Data Science @ IIIT Hyderabad",
        "Turning models into decisions — Power BI, SQL, Python",
        "Building agentic AI systems, RAG pipelines & LLM eval harnesses",
    ],
    researchInterests: [
        "Scaling laws",
        "Code generation",
        "AI safety and alignment",
        "A2A Agent Cards",
    ],
    socials: {
        github: "https://github.com/sairam3824",
        linkedin: "https://www.linkedin.com/in/sairam-maruri/",
        leetcodePrimary: "https://leetcode.com/u/programmer3824/",
        leetcodeSecondary: "https://leetcode.com/u/sairam3824/",
        codechef: "https://www.codechef.com/users/sairam2004",
        codeforces: "https://codeforces.com/profile/sairam3824",
        credly: "https://www.credly.com/users/sai-rama-linga-reddy-maruri.44a3ece0",
    },
} as const;

export const siteMetadata = {
    siteUrl: "https://www.saiii.in",
    applicationName: "Sai Ram Maruri Portfolio",
    defaultTitle: `${profileDetails.name} | ${profileDetails.shortRole}`,
    defaultDescription:
        "GenAI & ML Engineer and Business Analytics postgrad — turning data into business decisions. Production AI projects, BI dashboards, technical writing, and competitive programming by Sai Ram Maruri.",
    manifestDescription: "GenAI & ML Engineer · Business Analytics Portfolio",
    previewImage: "/preview.webp",
    previewImageType: "image/webp",
    twitterHandle: "@sairammaruri",
    copyrightYear: new Date().getUTCFullYear(),
    alumniOf: {
        name: "VIT-AP University",
        url: "https://vitap.ac.in",
    },
    knowsAbout: [
        "Artificial Intelligence",
        "Machine Learning",
        "Generative AI",
        "Business Analytics",
        "Data Science",
        "Power BI",
        "SQL",
        "Python",
        "AWS",
    ],
    keywords: [
        "Business Analyst",
        "Data Analyst",
        "AI Engineer",
        "GenAI",
        "Machine Learning",
        "Business Analytics",
        "Data Science",
        "Power BI",
        "Sairam Maruri",
    ],
    sameAs: [
        profileDetails.socials.github,
        profileDetails.socials.linkedin,
        profileDetails.socials.leetcodePrimary,
        profileDetails.socials.codechef,
        profileDetails.socials.codeforces,
    ],
} as const;
