export interface Skill {
    name: string;
    level: "Advanced" | "Intermediate" | "Beginner";
    url?: string;
    company?: string;
}

export interface SkillCategory {
    category: string;
    iconName: string;
    color: string;
    description: string;
    skills: Skill[];
}

export const skillCategories: SkillCategory[] = [
    {
        category: "Business Analytics & BI",
        iconName: "BarChart3",
        color: "amber",
        description: "Turning data into dashboards and decisions stakeholders can act on.",
        skills: [
            { name: "Power BI", level: "Advanced", url: "https://powerbi.microsoft.com/", company: "Microsoft" },
            { name: "Tableau", level: "Intermediate", url: "https://www.tableau.com/", company: "Salesforce" },
            { name: "SQL", level: "Advanced", url: "https://www.postgresql.org/docs/", company: "SQL" },
            { name: "Advanced Excel", level: "Advanced", url: "https://www.microsoft.com/microsoft-365/excel", company: "Microsoft" },
            { name: "DAX", level: "Intermediate", url: "https://learn.microsoft.com/dax/", company: "Microsoft" },
            { name: "Statistical Inference", level: "Advanced", url: "#", company: "Technique" },
            { name: "A/B Testing", level: "Advanced", url: "#", company: "Technique" },
            { name: "Time-Series Forecasting", level: "Advanced", url: "#", company: "Technique" },
            { name: "Predictive Modeling", level: "Advanced", url: "#", company: "Technique" },
            { name: "Customer Segmentation", level: "Advanced", url: "#", company: "Technique" },
            { name: "Churn & Cohort Analysis", level: "Advanced", url: "#", company: "Technique" },
            { name: "Data Storytelling", level: "Advanced", url: "#", company: "Technique" },
        ],
    },
    {
        category: "GenAI & LLMs",
        iconName: "Brain",
        color: "indigo",
        description: "Architecting intelligent systems with cutting-edge models.",
        skills: [
            { name: "Llama 3.1/3.2", level: "Advanced", url: "https://llama.meta.com/", company: "Meta" },
            { name: "Grok", level: "Advanced", url: "https://grok.x.ai/", company: "xAI" },
            { name: "GPT-4", level: "Advanced", url: "https://openai.com/gpt-4", company: "OpenAI" },
            { name: "Claude (Opus/Sonnet)", level: "Advanced", url: "https://www.anthropic.com/", company: "Anthropic" },
            { name: "Gemini Pro/Ultra", level: "Advanced", url: "https://deepmind.google/technologies/gemini/", company: "Google" },
            { name: "DeepSeek", level: "Advanced", url: "https://www.deepseek.com/", company: "DeepSeek" },
            { name: "Mistral", level: "Advanced", url: "https://mistral.ai/", company: "Mistral AI" },
            { name: "CodeLLaMA", level: "Advanced", url: "https://ai.meta.com/blog/code-llama-large-language-model-coding/", company: "Meta" },
            { name: "Qwen", level: "Advanced", url: "https://qwenlm.github.io/", company: "Alibaba" },
            { name: "Ollama", level: "Advanced", url: "https://ollama.com/", company: "Ollama" },
        ],
    },
    {
        category: "AI Coding",
        iconName: "Code2",
        color: "blue",
        description: "Next-gen AI coding assistants and environments.",
        skills: [
            { name: "Claude Code", level: "Advanced", url: "https://www.anthropic.com/", company: "Anthropic" },
            { name: "Cursor AI", level: "Advanced", url: "https://cursor.sh/", company: "Cursor" },
            { name: "Windsurf", level: "Advanced", url: "https://windsurf.ai/", company: "Codeium" },

            { name: "GitHub Copilot", level: "Advanced", url: "https://github.com/features/copilot", company: "GitHub" },
            { name: "Codex", level: "Advanced", url: "https://openai.com/blog/openai-codex", company: "OpenAI" },
            { name: "Aider", level: "Advanced", url: "https://aider.chat/", company: "Aider" },
            { name: "Kiro", level: "Intermediate", url: "#", company: "Kiro" },
            { name: "Antigravity", level: "Advanced", url: "#", company: "Google DeepMind" },
        ],
    },
    {
        category: "Agent Frameworks",
        iconName: "Zap",
        color: "rose",
        description: "Building autonomous agents and multi-agent systems.",
        skills: [
            { name: "LangChain", level: "Advanced", url: "https://www.langchain.com/", company: "LangChain" },
            { name: "LangGraph", level: "Advanced", url: "https://langchain-ai.github.io/langgraph/", company: "LangChain" },
            { name: "n8n", level: "Advanced", url: "https://n8n.io/", company: "n8n" },
            { name: "Zapier", level: "Advanced", url: "https://zapier.com/", company: "Zapier" },
            { name: "OpenAI Agent SDK", level: "Advanced", url: "https://platform.openai.com/docs/assistants/overview", company: "OpenAI" },
            { name: "AutoGen", level: "Advanced", url: "https://microsoft.github.io/autogen/", company: "Microsoft" },
            { name: "A2A Agent", level: "Advanced", url: "https://a2a-protocol.org/", company: "A2A Protocol" },
            { name: "MCP", level: "Advanced", url: "https://modelcontextprotocol.io/", company: "Anthropic" },
            { name: "CrewAI", level: "Advanced", url: "https://www.crewai.com/", company: "CrewAI" },
            { name: "OpenRouter", level: "Advanced", url: "https://openrouter.ai/", company: "OpenRouter" },
            { name: "Tavily", level: "Advanced", url: "https://tavily.com/", company: "Tavily" },
            { name: "Agentic Workflows", level: "Advanced", url: "#", company: "Technique" },
        ],
    },
    {
        category: "Cloud & DevOps",
        iconName: "Cloud",
        color: "sky",
        description: "Deploying and scaling applications on modern infrastructure.",
        skills: [
            { name: "AWS Bedrock", level: "Advanced", url: "https://aws.amazon.com/bedrock/", company: "AWS" },
            { name: "AWS SageMaker", level: "Advanced", url: "https://aws.amazon.com/sagemaker/", company: "AWS" },
            { name: "AWS Lambda", level: "Advanced", url: "https://aws.amazon.com/lambda/", company: "AWS" },
            { name: "AWS EC2", level: "Advanced", url: "https://aws.amazon.com/ec2/", company: "AWS" },
            { name: "Vertex AI", level: "Advanced", url: "https://cloud.google.com/vertex-ai", company: "Google Cloud" },
            { name: "Docker", level: "Advanced", url: "https://www.docker.com/", company: "Docker" },
            { name: "Kubernetes", level: "Advanced", url: "https://kubernetes.io/", company: "CNCF" },
            { name: "Terraform", level: "Advanced", url: "https://www.terraform.io/", company: "HashiCorp" },
        ],
    },
    {
        category: "Vector DB",
        iconName: "Database",
        color: "emerald",
        description: "Efficient storage and retrieval for high-dimensional vectors.",
        skills: [
            { name: "Pinecone", level: "Advanced", url: "https://www.pinecone.io/", company: "Pinecone" },
            { name: "Chroma", level: "Advanced", url: "https://www.trychroma.com/", company: "Chroma" },
            { name: "Qdrant", level: "Advanced", url: "https://qdrant.tech/", company: "Qdrant" },
            { name: "FAISS", level: "Advanced", url: "https://faiss.ai/", company: "Meta" },
            { name: "pgvector", level: "Advanced", url: "https://github.com/pgvector/pgvector", company: "PostgreSQL" },
            { name: "text-embedding-3-small", level: "Advanced", url: "https://platform.openai.com/docs/guides/embeddings", company: "OpenAI" },
            { name: "all-MiniLM-L6-v2", level: "Advanced", url: "https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2", company: "Hugging Face" },
        ],
    },
    {
        category: "Intelligence Stack",
        iconName: "Brain",
        color: "amber",
        description: "Developing predictive models and computer vision pipelines.",
        skills: [
            { name: "TensorFlow", level: "Intermediate", url: "https://www.tensorflow.org/", company: "Google" },
            { name: "PyTorch", level: "Intermediate", url: "https://pytorch.org/", company: "Meta" },
            { name: "Keras", level: "Intermediate", url: "https://keras.io/", company: "Keras" },
            { name: "scikit-learn", level: "Intermediate", url: "https://scikit-learn.org/", company: "scikit-learn" },
            { name: "XGBoost", level: "Advanced", url: "https://xgboost.ai/", company: "DMLC" },
            { name: "LightGBM", level: "Advanced", url: "https://lightgbm.readthedocs.io/", company: "Microsoft" },
            { name: "CatBoost", level: "Advanced", url: "https://catboost.ai/", company: "Yandex" },
            { name: "pandas", level: "Advanced", url: "https://pandas.pydata.org/", company: "pandas" },
            { name: "spaCy", level: "Advanced", url: "https://spacy.io/", company: "Explosion AI" },
            { name: "Stable-Baselines3", level: "Advanced", url: "https://stable-baselines3.readthedocs.io/", company: "SB3" },
            { name: "Gymnasium", level: "Advanced", url: "https://gymnasium.farama.org/", company: "Farama" },
            { name: "OpenCV", level: "Advanced", url: "https://opencv.org/", company: "OpenCV" },
            { name: "HuggingFace", level: "Advanced", url: "https://huggingface.co/", company: "Hugging Face" },
            { name: "Hugging Face Transformers", level: "Advanced", url: "https://huggingface.co/docs/transformers", company: "Hugging Face" },
            { name: "RAG", level: "Advanced", url: "https://arxiv.org/abs/2005.11401", company: "Technique" },
            { name: "Fine-tuning", level: "Advanced", url: "https://platform.openai.com/docs/guides/fine-tuning", company: "Technique" },
            { name: "Prompt Engineering", level: "Advanced", url: "https://www.promptingguide.ai/", company: "Technique" },
            { name: "Neural Networks", level: "Advanced", url: "#", company: "Technique" },
            { name: "Model Deployment", level: "Advanced", url: "#", company: "Technique" },
        ],
    },
    {
        category: "Explainable AI & Research",
        iconName: "Brain",
        color: "violet",
        description: "Interpretability, topological analysis, and novel architectures from research work.",
        skills: [
            { name: "SHAP", level: "Advanced", url: "https://shap.readthedocs.io/", company: "SHAP" },
            { name: "Grad-CAM / GradCAM++", level: "Advanced", url: "https://arxiv.org/abs/1610.02391", company: "Technique" },
            { name: "Topological Data Analysis", level: "Advanced", url: "https://en.wikipedia.org/wiki/Topological_data_analysis", company: "Technique" },
            { name: "Persistent Homology (ripser)", level: "Advanced", url: "https://ripser.scikit-tda.org/", company: "scikit-tda" },
            { name: "Tensor Decomposition (TensorLy)", level: "Advanced", url: "http://tensorly.org/", company: "TensorLy" },
            { name: "Kolmogorov-Arnold Networks (KAN)", level: "Advanced", url: "https://arxiv.org/abs/2404.19756", company: "Research" },
        ],
    },
    {
        category: "Full-Stack Dev",
        iconName: "Monitor",
        color: "sky",
        description: "Building end-to-end web applications with modern frameworks.",
        skills: [
            { name: "React", level: "Advanced", url: "https://react.dev/", company: "Meta" },
            { name: "Next.js", level: "Advanced", url: "https://nextjs.org/", company: "Vercel" },
            { name: "TypeScript", level: "Advanced", url: "https://www.typescriptlang.org/", company: "Microsoft" },
            { name: "Tailwind CSS", level: "Advanced", url: "https://tailwindcss.com/", company: "Tailwind Labs" },
            { name: "Vite", level: "Advanced", url: "https://vitejs.dev/", company: "Vite" },
            { name: "Framer Motion", level: "Advanced", url: "https://www.framer.com/motion/", company: "Framer" },
            { name: "shadcn/ui", level: "Advanced", url: "https://ui.shadcn.com/", company: "shadcn" },
            { name: "Recharts", level: "Advanced", url: "https://recharts.org/", company: "Recharts" },
            { name: "Electron", level: "Advanced", url: "https://www.electronjs.org/", company: "OpenJS" },
            { name: "Python", level: "Advanced", url: "https://www.python.org/", company: "PSF" },
            { name: "FastAPI", level: "Advanced", url: "https://fastapi.tiangolo.com/", company: "Tiangolo" },
            { name: "Flask", level: "Advanced", url: "https://flask.palletsprojects.com/", company: "Pallets" },
            { name: "Django", level: "Advanced", url: "https://www.djangoproject.com/", company: "Django" },
            { name: "Django REST", level: "Advanced", url: "https://www.django-rest-framework.org/", company: "Django REST Framework" },
            { name: "Node.js", level: "Advanced", url: "https://nodejs.org/", company: "OpenJS" },
            { name: "Java", level: "Advanced", url: "https://www.java.com/", company: "Oracle" },
            { name: "C++", level: "Advanced", url: "https://isocpp.org/", company: "ISO C++" },
            { name: "Go", level: "Advanced", url: "https://go.dev/", company: "Google" },
            { name: "PostgreSQL", level: "Advanced", url: "https://www.postgresql.org/", company: "PostgreSQL" },
            { name: "SQLite", level: "Advanced", url: "https://www.sqlite.org/", company: "SQLite" },
            { name: "SQL", level: "Advanced", url: "https://www.postgresql.org/docs/", company: "SQL" },
            { name: "Prisma", level: "Advanced", url: "https://www.prisma.io/", company: "Prisma" },
            { name: "Streamlit", level: "Advanced", url: "https://streamlit.io/", company: "Streamlit" },
        ],
    },
    {
        category: "Infra & Delivery",
        iconName: "Server",
        color: "slate",
        description: "Production readiness, pipelines, and core engineering tools.",
        skills: [
            { name: "Git", level: "Advanced", url: "https://git-scm.com/", company: "Git" },
            { name: "CI/CD", level: "Advanced", url: "#", company: "Delivery" },
            { name: "GitHub Actions", level: "Advanced", url: "https://github.com/features/actions", company: "GitHub" },
            { name: "Pytest", level: "Advanced", url: "https://pytest.org/", company: "Pytest" },
            { name: "Selenium", level: "Advanced", url: "https://www.selenium.dev/", company: "Selenium" },
            { name: "WebSockets", level: "Advanced", url: "https://developer.mozilla.org/docs/Web/API/WebSockets_API", company: "Web Standard" },
            { name: "Server-Sent Events", level: "Advanced", url: "https://developer.mozilla.org/docs/Web/API/Server-sent_events", company: "Web Standard" },
            { name: "Prometheus", level: "Advanced", url: "https://prometheus.io/", company: "CNCF" },
            { name: "Zod", level: "Advanced", url: "https://zod.dev/", company: "Zod" },
            { name: "Redis", level: "Advanced", url: "https://redis.io/", company: "Redis" },
            { name: "Celery", level: "Advanced", url: "https://docs.celeryq.dev/", company: "Celery" },
            { name: "Kafka", level: "Advanced", url: "https://kafka.apache.org/", company: "Apache" },
            { name: "Supabase", level: "Advanced", url: "https://supabase.com/", company: "Supabase" },
            { name: "Nginx", level: "Advanced", url: "https://nginx.org/", company: "Nginx" },
            { name: "Vercel", level: "Advanced", url: "https://vercel.com/", company: "Vercel" },
            { name: "AWS RDS", level: "Advanced", url: "https://aws.amazon.com/rds/", company: "AWS" },
            { name: "AWS S3", level: "Advanced", url: "https://aws.amazon.com/s3/", company: "AWS" },
        ],
    },
];
